export type ChoiceOption = { key: string; label: string };
export type Question =
  | { id: string; type: "choice"; section: string; prompt: string; options: ChoiceOption[] }
  | { id: string; type: "open"; section: string; prompt: string; placeholder?: string };

// Perfil comportamental — 10 questões (7 múltipla escolha + 3 abertas)
export const perfilQuestions: Question[] = [
  {
    id: "p1",
    type: "choice",
    section: "Interação e Hábitos de Uso",
    prompt: "Com que frequência você utiliza ferramentas de IA Generativa (ChatGPT, Gemini, Claude, Copilot, etc.)?",
    options: [
      { key: "A", label: "Nunca: não tenho contato ou não sei como acessar." },
      { key: "B", label: "Raramente: menos de uma vez por semana, apenas por curiosidade." },
      { key: "C", label: "Ocasionalmente: algumas vezes por semana para tarefas pontuais." },
      { key: "D", label: "Frequentemente: quase todos os dias para auxílio em tarefas." },
      { key: "E", label: "Diariamente: é uma ferramenta central no meu fluxo de trabalho/estudo." },
    ],
  },
  {
    id: "p2",
    type: "choice",
    section: "Interação e Hábitos de Uso",
    prompt: "Qual o seu principal objetivo ao utilizar IA no momento?",
    options: [
      { key: "A", label: "Ganhar tempo em tarefas repetitivas e burocráticas." },
      { key: "B", label: "Melhorar a qualidade e criatividade dos meus textos/projetos." },
      { key: "C", label: "Aprender novos assuntos de forma mais rápida e didática." },
      { key: "D", label: "Resolver problemas técnicos ou de programação." },
      { key: "E", label: "Apenas explorar as capacidades da tecnologia por curiosidade." },
    ],
  },
  {
    id: "p3",
    type: "choice",
    section: "Comportamento e Consumo de Informação",
    prompt: "\"Eu busco ativamente aprender sobre as atualizações e novos recursos das ferramentas de IA que utilizo.\"",
    options: [
      { key: "A", label: "Discordo totalmente" },
      { key: "B", label: "Discordo parcialmente" },
      { key: "C", label: "Neutro / indiferente" },
      { key: "D", label: "Concordo parcialmente" },
      { key: "E", label: "Concordo totalmente" },
    ],
  },
  {
    id: "p4",
    type: "choice",
    section: "Comportamento e Consumo de Informação",
    prompt: "Ao receber uma resposta de uma IA, qual é o seu comportamento padrão de validação?",
    options: [
      { key: "A", label: "Confio plenamente e a utilizo sem alterações." },
      { key: "B", label: "Leitura rápida pra ver se faz sentido, raramente checo fontes." },
      { key: "C", label: "Verifico informações suspeitas ou críticas em outras fontes." },
      { key: "D", label: "Sempre valido os pontos principais e ajusto o tom da resposta." },
      { key: "E", label: "Utilizo apenas como rascunho inicial, reescrevendo quase tudo." },
    ],
  },
  {
    id: "p5",
    type: "choice",
    section: "Percepção de Valor e Ética",
    prompt: "Qual o seu nível de conforto em delegar tarefas importantes para uma IA?",
    options: [
      { key: "A", label: "Muito desconfortável; prefiro fazer tudo manualmente." },
      { key: "B", label: "Pouco confortável; delego apenas tarefas irrelevantes." },
      { key: "C", label: "Neutro; depende muito da tarefa e da ferramenta." },
      { key: "D", label: "Confortável; delego tarefas que exigem análise, mas reviso tudo." },
      { key: "E", label: "Muito confortável; confio na IA para otimizar grande parte do trabalho." },
    ],
  },
  {
    id: "p6",
    type: "choice",
    section: "Percepção de Valor e Ética",
    prompt: "Sobre o impacto da IA no mercado de trabalho, qual afirmação melhor descreve sua visão?",
    options: [
      { key: "A", label: "A IA é uma ameaça que irá substituir a maioria das profissões humanas." },
      { key: "B", label: "A IA trará mudanças negativas, dificultando a empregabilidade." },
      { key: "C", label: "A IA é uma ferramenta neutra; o impacto depende de quem a usa." },
      { key: "D", label: "A IA é uma oportunidade de evolução, automatizando o que é chato." },
      { key: "E", label: "A IA é essencial para o futuro e criará novas e melhores profissões." },
    ],
  },
  {
    id: "p7",
    type: "choice",
    section: "Percepção de Valor e Ética",
    prompt: "Qual o seu nível de familiaridade técnica inicial (termos como ML, LLM, Deep Learning)?",
    options: [
      { key: "A", label: "Nunca ouvi falar desses termos." },
      { key: "B", label: "Já ouvi falar, mas não sei explicar o que significam." },
      { key: "C", label: "Entendo o conceito básico de alguns, mas não de todos." },
      { key: "D", label: "Tenho uma boa noção teórica e sei diferenciar os principais termos." },
      { key: "E", label: "Tenho conhecimento aprofundado e consigo explicar tecnicamente." },
    ],
  },
  {
    id: "p_open_1",
    type: "open",
    section: "Reflexão Aberta",
    prompt: "Descreva, em poucas linhas, uma situação real em que a IA te ajudou (ou poderia ter ajudado) e o que você sentiu ao usar.",
    placeholder: "Compartilhe sua experiência...",
  },
  {
    id: "p_open_2",
    type: "open",
    section: "Reflexão Aberta",
    prompt: "O que você espera aprender ou conquistar dominando ferramentas de Inteligência Artificial?",
    placeholder: "Suas expectativas e objetivos...",
  },
  {
    id: "p_open_3",
    type: "open",
    section: "Reflexão Aberta",
    prompt: "Qual a sua maior dúvida, receio ou bloqueio atual em relação ao uso de IA no seu dia a dia?",
    placeholder: "Compartilhe suas dúvidas ou receios...",
  },
];

// Avaliação técnica — 10 questões (7 múltipla escolha + 3 abertas) com gabarito para pontuação
export const tecnicoQuestions: (Question & { correct?: string })[] = [
  {
    id: "t1",
    type: "choice",
    section: "Conceitos Fundamentais da IA",
    prompt: "Qual das seguintes opções melhor define Inteligência Artificial (IA)?",
    correct: "B",
    options: [
      { key: "A", label: "Um software que apenas automatiza tarefas repetitivas." },
      { key: "B", label: "Um campo da ciência da computação que busca criar sistemas capazes de realizar tarefas que exigiriam inteligência humana." },
      { key: "C", label: "Uma tecnologia que permite que robôs pensem e sintam como humanos." },
      { key: "D", label: "Um banco de dados gigante para armazenar informações." },
    ],
  },
  {
    id: "t2",
    type: "choice",
    section: "Conceitos Fundamentais da IA",
    prompt: "Qual é a principal diferença entre um software tradicional e um sistema de IA?",
    correct: "B",
    options: [
      { key: "A", label: "Software tradicional é sempre mais rápido que a IA." },
      { key: "B", label: "Software tradicional segue regras fixas, enquanto a IA aprende com dados e experiências." },
      { key: "C", label: "A IA não precisa de programação, o software tradicional sim." },
      { key: "D", label: "Software tradicional é offline, a IA é sempre online." },
    ],
  },
  {
    id: "t3",
    type: "choice",
    section: "Conceitos Fundamentais da IA",
    prompt: "Qual o papel dos dados no funcionamento de um sistema de IA?",
    correct: "C",
    options: [
      { key: "A", label: "São apenas um subproduto do processamento da IA." },
      { key: "B", label: "Servem para armazenar os resultados finais gerados pela IA." },
      { key: "C", label: "São o \"combustível\" essencial que a IA utiliza para aprender, identificar padrões e tomar decisões." },
      { key: "D", label: "São usados apenas para a interface gráfica do usuário." },
    ],
  },
  {
    id: "t4",
    type: "choice",
    section: "Machine Learning e Deep Learning",
    prompt: "Qual das opções melhor define \"Machine Learning\" (Aprendizado de Máquina)?",
    correct: "B",
    options: [
      { key: "A", label: "Um processo onde robôs aprendem a se mover fisicamente." },
      { key: "B", label: "Um subcampo da IA que permite aos sistemas aprenderem com dados, sem serem explicitamente programados para cada regra." },
      { key: "C", label: "Uma técnica de programação que exige que o desenvolvedor escreva cada regra de decisão." },
      { key: "D", label: "O processo de ensinar um computador a jogar xadrez manualmente." },
    ],
  },
  {
    id: "t5",
    type: "choice",
    section: "Machine Learning e Deep Learning",
    prompt: "Qual a relação correta entre \"Machine Learning\" e \"Deep Learning\"?",
    correct: "C",
    options: [
      { key: "A", label: "São termos sinônimos e podem ser usados de forma intercambiável." },
      { key: "B", label: "Deep Learning é uma técnica mais antiga que o Machine Learning." },
      { key: "C", label: "Deep Learning é um subcampo do Machine Learning que utiliza redes neurais com múltiplas camadas." },
      { key: "D", label: "Machine Learning é um subcampo do Deep Learning." },
    ],
  },
  {
    id: "t6",
    type: "choice",
    section: "IA Generativa e Termos Específicos",
    prompt: "O que significa a sigla \"LLM\" no contexto da IA?",
    correct: "B",
    options: [
      { key: "A", label: "Linguagem de Lógica Matemática" },
      { key: "B", label: "Large Language Model (Modelo de Linguagem Grande)" },
      { key: "C", label: "Local Learning Machine" },
      { key: "D", label: "Light Learning Module" },
    ],
  },
  {
    id: "t7",
    type: "choice",
    section: "IA Generativa e Termos Específicos",
    prompt: "O que o termo \"Alucinação\" descreve no contexto da IA?",
    correct: "B",
    options: [
      { key: "A", label: "Um erro de sistema que faz a IA parar de funcionar." },
      { key: "B", label: "Quando a IA gera uma resposta que parece correta e confiante, mas é factualmente falsa ou inventada." },
      { key: "C", label: "Quando a IA começa a falar em outros idiomas sem ser solicitada." },
      { key: "D", label: "O mecanismo de segurança que impede a IA de responder perguntas antiéticas." },
    ],
  },
  {
    id: "t_open_1",
    type: "open",
    section: "Reflexão Aberta",
    prompt: "Em suas palavras, explique o que você entende por \"Inteligência Artificial Generativa\" e dê um exemplo prático de uso.",
    placeholder: "Sua explicação...",
  },
  {
    id: "t_open_2",
    type: "open",
    section: "Reflexão Aberta",
    prompt: "O que é \"Engenharia de Prompt\" e por que ela é importante para obter bons resultados de uma IA Generativa?",
    placeholder: "Sua resposta...",
  },
  {
    id: "t_open_3",
    type: "open",
    section: "Reflexão Aberta",
    prompt: "Cite um exemplo de aplicação de IA no dia a dia e explique brevemente como você imagina que ela funciona por trás dos panos.",
    placeholder: "Exemplo e explicação...",
  },
];
