/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TecnicoRouteImport } from './routes/tecnico'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as DesafioRouteImport } from './routes/desafio'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app/projects'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicoRoute = TecnicoRouteImport.update({
  id: '/tecnico',
  path: '/tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafioRoute = DesafioRouteImport.update({
  id: '/desafio',
  path: '/desafio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desafio': typeof DesafioRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnico': typeof TecnicoRoute
  '/upload': typeof UploadRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desafio': typeof DesafioRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnico': typeof TecnicoRoute
  '/upload': typeof UploadRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/desafio': typeof DesafioRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tecnico': typeof TecnicoRoute
  '/upload': typeof UploadRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desafio'
    | '/perfil'
    | '/sitemap.xml'
    | '/tecnico'
    | '/upload'
    | '/app'
    | '/app/profile'
    | '/app/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desafio'
    | '/perfil'
    | '/sitemap.xml'
    | '/tecnico'
    | '/upload'
    | '/app'
    | '/app/profile'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/desafio'
    | '/perfil'
    | '/sitemap.xml'
    | '/tecnico'
    | '/upload'
    | '/_authenticated/app'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DesafioRoute: typeof DesafioRoute
  PerfilRoute: typeof PerfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TecnicoRoute: typeof TecnicoRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnico': {
      id: '/tecnico'
      path: '/tecnico'
      fullPath: '/tecnico'
      preLoaderRoute: typeof TecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafio': {
      id: '/desafio'
      path: '/desafio'
      fullPath: '/desafio'
      preLoaderRoute: typeof DesafioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DesafioRoute: DesafioRoute,
  PerfilRoute: PerfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TecnicoRoute: TecnicoRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
